# Generated by Django 2.0 on 2018-06-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok1', '0003_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
