# Generated by Django 3.2.8 on 2022-10-07 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blok1', '0006_site_maintenance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site_maintenance',
            options={'verbose_name': 'БД Техобслуживание сайта', 'verbose_name_plural': 'Записи в БД Site_maintenance'},
        ),
    ]
