# Generated by Django 3.2.8 on 2022-08-22 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market_Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name_Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_market', models.IntegerField(default=0)),
                ('currency', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('symbol', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('image_currency', models.ImageField(blank=True, max_length=255, null=True, upload_to='image_currency/')),
                ('wallet', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('market_exchange', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blok2.market_exchange')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('news', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prices_Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_currency_sale_id', models.IntegerField(default=0)),
                ('name_currency_sale_currency', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('min_buy', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('max_buy', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('kurs_buy', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('min_sell', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('max_sell', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('kurs_sell', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('id_pair_market', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name_currency', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blok2.name_currency')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='news_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('to_news', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blok2.news')),
            ],
        ),
        migrations.CreateModel(
            name='Balance_Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_amount', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name_currency', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blok2.name_currency')),
            ],
        ),
    ]
