# Generated by Django 3.2.8 on 2022-08-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(default=0)),
                ('id_pair_market', models.IntegerField(default=0)),
                ('name_currency_buy_id', models.IntegerField(default=0)),
                ('name_currency_buy_currency', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('sum_currency_buy', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('wallet_currency_buy', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('name_currency_sell_id', models.IntegerField(default=0)),
                ('name_currency_sell_currency', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('sum_currency_sell', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('wallet_currency_sell', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('kurs_sell', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('kurs_buy_fact', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('sum_currency_buy_fact', models.DecimalField(decimal_places=10, default=0, max_digits=30)),
                ('wallet_fact', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('status', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
