# Generated by Django 3.2.8 on 2022-09-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok2', '0002_exchange_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange_list',
            name='qr_wallet',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='qr/'),
        ),
    ]
