# Generated by Django 3.2.8 on 2022-09-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blok2', '0003_exchange_list_qr_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange_list',
            name='qr_wallet',
        ),
    ]
