# Generated by Django 3.2.8 on 2022-09-29 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blok2', '0004_remove_exchange_list_qr_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices_currency',
            name='market_exchange',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='blok2.market_exchange'),
        ),
    ]
