# Generated by Django 3.2.8 on 2022-09-29 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blok2', '0005_prices_currency_market_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices_currency',
            name='market_exchange',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='blok2.market_exchange'),
        ),
    ]
