# Generated by Django 3.2.8 on 2022-10-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blok2', '0006_alter_prices_currency_market_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices_currency',
            name='max_sell',
        ),
        migrations.RemoveField(
            model_name='prices_currency',
            name='min_sell',
        ),
    ]
