# Generated by Django 3.2.8 on 2022-10-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blok2', '0007_auto_20221010_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices_currency',
            name='kurs_buy',
        ),
    ]
